
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-10
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-issue29-studenstaffrepo-backend","number":40,"title":"Kham: add backend for creation option (student/staff)","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/40"},{"author":{"id":"MDQ6VXNlcjMwMDI4NDg4","is_bot":false,"login":"Cobalt396","name":"Joseph Neamati"},"headRefName":"jn-sanitizeEmailAddrsInBackend","number":39,"title":"Sanitize Email Addresses in Backend Endpoints","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/39"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-issue26-optional-for-14","number":31,"title":"Issue 26: Optional for 14 \"Change simple dropdown in add team member to have search and filters\" using Typeahead","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/31"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-issue20-section-post-put","number":28,"title":"Issue 20: Add update of \"section\" to POST and PUT for roster","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/28"},{"author":{"id":"MDQ6VXNlcjcxMzU3MjUx","is_bot":false,"login":"Sarahbob","name":""},"headRefName":"sy-courseStaffOptionalRemoveFromOrg","number":23,"title":"Added removeFromOrg Parameter to Course Staff Delete","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/23"},{"author":{"id":"MDQ6VXNlcjE2ODY4MzAx","is_bot":false,"login":"Kancho-Baev","name":"KB"},"headRefName":"refactor/issue-13-refactor-signinpage","number":21,"title":"Issue 13: Refactoring","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/21"}]
