
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-10
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-issue15-eslint","number":47,"title":"Issue 15: Reintroduce React ESLint Rules","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/47"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-issue30-studentstaffrepo-frontend","number":46,"title":"Issue 30: Modify the frontend to give the user an option for student/staff dropdown in assignment ","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/46"},{"author":{"id":"U_kgDOCMvSuQ","is_bot":false,"login":"keigoomura","name":"Keigo Omura"},"headRefName":"Keigo-CreateAssignmentsDB","number":45,"title":"Issue 32: Create Assignments Table for Assignments EPIC","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/45"},{"author":{"id":"MDQ6VXNlcjcxMzU3MjUx","is_bot":false,"login":"Sarahbob","name":""},"headRefName":"sy-courseStaffDeleteCheckbox","number":44,"title":"Issue 22: Added Confirmation Checkbox to CourseStaff Delete","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/44"},{"author":{"id":"U_kgDOCMvSuQ","is_bot":false,"login":"keigoomura","name":"Keigo Omura"},"headRefName":"Keigo-CreateSettingsTab","number":43,"title":"Issue 18: Add Settings Tab to InstructorCourseShowPage","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/43"},{"author":{"id":"U_kgDOCMvSuQ","is_bot":false,"login":"keigoomura","name":"Keigo Omura"},"headRefName":"Keigo-CSVUpload","number":42,"title":"Issue 19: Updating CSV Upload Format Documentation","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/42"},{"author":{"id":"MDQ6VXNlcjE2ODY4MzAx","is_bot":false,"login":"Kancho-Baev","name":"KB"},"headRefName":"refactor/issue-13-refactor-signinpage","number":21,"title":"Issue 13: Refactoring","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/21"}]
