
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-10
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwMDI4NDg4","is_bot":false,"login":"Cobalt396","name":"Joseph Neamati"},"headRefName":"jn-fixCourseStaffControllerTestNames","number":52,"title":"Issue 51 - Fixed names of CourseStaffControllerTests methods for PUT endpoint","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/52"},{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"saanvi-assignmentDELETE","number":50,"title":"Issue 35 - Assignment DELETE Endpoint and Tests","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/50"},{"author":{"id":"MDQ6VXNlcjE2ODY4MzAx","is_bot":false,"login":"Kancho-Baev","name":"KB"},"headRefName":"refactor/issue-13-refactor-signinpage","number":21,"title":"Issue 13: Refactoring","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-10/pull/21"}]
